---
- name: install apache2
  apt: 
    name: apache2 
    state: present 
  register: apache_output

- name: show intall apache
  debug:
    msg: "{{apache_output}}"

- name: start service apache
  service:
    name: apache2
    state: started 
  register: service_apache_output

- name: debug service apache
  debug:
    msg: "{{service_apache_output}}"

- name: check service apache
  shell: service apache2 status
  register: service_apache_output
    
- name: show status service apache
  debug:
    msg: "{{service_apache_output}}"
