---
- name: Installation des elements pour host1
  hosts: host1
  remote_user: root
  tasks:
          #  - name: Installer Vim
          #apt: 
          #name: vim
          #state: present 
          #register: capture
    - name: Check that a page returns a status 200 and fail if the word AWESOME is not in the page contents
      uri:
        url: "http://{{ ansible_host }}"
        return_content: yes
      register: result 
      failed_when: "200 != result.status"
        #:{{ port | default(80) }} 
        #register: result

    - name: debug
      debug:
        msg: 
          - "{{result.content}}"
          - "{{result.server}}"
          - "{{result.status}}"
          - "{{result.url}}"
