---
- hosts: webserver
  remote_user: root
  vars_files:
          - "vars/{{env}}_vars.yml"
          - "vars/{{env}}_vault.yml"
  tasks:
    - name: "Add user {{user}}" 
      user:
        name: "{{user}}"
        password: "{{pass | password_hash('sha512')}}"
        state: present 
      register: adduser_output

    - name: debug user
      debug:
        msg: "{{adduser_output}}"
