---
- name: install apache2
  apt: 
    name: apache2 
    update_cache: yes 
    state: "{{status_apache}}" 
  register: apache_output

- name: show intall apache
  debug:
    msg: "{{apache_output}}"

- name: Copy toto.txt
  copy:
    src: "files/toto.txt"
    dest: "/tmp/toto.txt"
  register: copy_txt

- name: show copy txt
  debug:
    msg: "{{copy_txt}}"

- name: Copy index
  template:
    src: 'templates/index.html.j2'
    dest: '/var/www/html/index.html'
  register: copy_index
  notify: 
    - restart service apache
    - debug service apache
    - check service apache
    - show status service apache
         
- name: show copy index 
  debug:
    msg: "{{copy_index}}"

- name: Check that a page returns a status 200
  uri:
    url: "http://{{ ansible_host }}"
    status_code: 200
