---
- hosts: webserver
  remote_user: root
  vars_files:
          - "vars/{{env}}_vars.yml"
          - "vars/{{env}}_vault.yml"
  tasks:
    - name: "Add user in {{env}}" 
      user:
        name: "{{item.name}}"
        password: "{{item.password}}"
        state: present 
      register: adduser_output
      loop:
        - name: "{{user}}" 
          password: "{{pass}}"
        - name: "{{user2}}"
          password: "{{pass2}}"
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: debug user
      debug:
        msg: "{{adduser_output}}"
